[package]
name = "todos"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures = "0.3"
sqlx = { version = "0.6.1", features = ["sqlite", "runtime-tokio-rustls", "offline"] }
tokio = { version = "1.20.0", features = ["macros"]}
