on:
  push:
    branches:
      - main

name: Main

jobs:
  lint:
    name: Lint Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1.3.0
      - name: Run clippy
        run: cargo clippy -- -D warnings

  style:
    name: Check Rust style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1.3.0
      - name: Run rustfmt
        run: cargo fmt --all -- --check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1.3.0
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --version=0.6.1 --no-default-features -F sqlite -F rustls
      - name: Setup python
        uses: actions/setup-python@v3
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Test code
        run: cargo test

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  release-please:
    runs-on: ubuntu-latest
    needs: [lint, style, test, pre-commit]
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: pre-commit-sqlx-prepare
          bump-minor-pre-major: true
      - uses: actions/checkout@v3
      - name: Tag major and minor versions in Git
        if: ${{ steps.release.outputs.release_created }}
        uses: jacobsvante/tag-major-minor-action@v0
        with:
          major: ${{ steps.release.outputs.major }}
          minor: ${{ steps.release.outputs.minor }}
